### ISSUE TITLE
Bot Accept any offer

### ISSUE THREAD

**Issue by TheFryck** [pepzwee/steam-overpay-bot#1]
Hello the bot accept any offer and i dont know why

**Comment by LELManiac** [comment]
Did you figure out why? I would like to know because I am experiencing the same problem.

**Comment by pepzwee** [comment]
@LELManiac Are you using it with the latest updates?

**Comment by LELManiac** [comment]
Yes

**Comment by pepzwee** [comment]
I'll need more information on what kind of trade you are doing.

**Comment by LELManiac** [comment]
Accept only on overpay.
User items valued at 95% while bot items at 100%.

**Comment by LELManiac** [comment]
Also as a suggestion you should make chat commands, like !help and !info.

**Comment by pepzwee** [comment]
If you are trading as an admin (specified in config) then the bot will accept all offers. So far I still don't have any information on what kind of trade you made (if it's not an admin user) that got accepted where it should not have.

**Comment by LELManiac** [comment]
Well I first test as an ordinary user before hosting it 24/7.
That's when it accepted everything.
