### ISSUE TITLE
Adding new features?

### ISSUE THREAD

**Issue by abrahame** [pepzwee/steam-overpay-bot#3]
Hello,
Is there any possibilities to add minimum value to an item rather than minimum value.
I'm questioning because min value you can put many 0.03$ cases to get to min value for example 0.5$, rather that minimum value price per item.
Thanks.

**Comment by pepzwee** [comment]
It's possible. This is a basic script where I will not add any additional features.
You have two options:

1. Add the feature yourself and make a pull request if you want it to be included in this repository.
2. Contact me privately and I'll add it for 5 keys.
